### ISSUE TITLE
Node using high amounts of CPU

### ISSUE THREAD

**Issue by eamondawes** [ibmruntimes/node#104] opened 2018-06-07 12:12 UTC
We have experienced node using over 50% of the CPU and clogging up our system. After working with IBM it seems like the latest version, 6.14.2, may solve our issue. I will install that version and watch out for this error again. Creating GitHub issue for community visibility.

**Comment by ghost** [comment] 2018-06-27 13:34
Hi Guys - 

Any update on tracking this down?

**Comment by jBarz** [comment] 2018-06-27 23:13
hi @rocketjon,
We noticed excessive cpu usage issues in 6.14.1 and had a resolution in 6.14.2.
@eamondawes Have you seen this occur with 6.14.2?
Another edge case was found in 6.14.2 and fixed in 6.14.3 (which comes out either this week or next week)

**Comment by jBarz** [comment] 2018-06-29 15:41
6.14.3 has just been released. I would suggest upgrading to evaluate that as well.

**Comment by eamondawes** [comment] 2018-07-02 19:51
I upgraded to 6.14.3 I'll keep an eye out for any issues

**Comment by jBarz** [comment] 2018-07-24 15:31
Hi @eamondawes, how is 6.14.3 doing?
Are we in a position to close this issue?

**Comment by eamondawes** [comment] 2018-07-24 15:32
I haven't heard from anyone about abnormally high CPU usage. I'm ok to close this.

**Comment by jBarz** [comment] 2018-07-24 15:33
ok, thanks. Please re-open if necessary.

**Comment by eamondawes** [comment] 2018-09-13 14:42
We have seen this come up again on 6.14.3
What do you want to know to go forward?

**Comment by mhdawson** [comment] 2018-09-13 14:52
@joransiu, @mmallick-ca FYI, since @jBarz is no longer around.

**Comment by ghost** [comment] 2018-09-13 16:01
FYIi - we are working with @mmallick-ca via email to provide documentation and steps to reproduce.

**Comment by patbossman** [comment] 2018-09-18 14:18
I also see this issue fairly regularly.  What doc could I collect to support investigation?  @joransiu I could also give you access to a system if that helps.

**Comment by joransiu** [comment] 2018-09-18 15:57
@patbossman : That would be useful... I'll reach out to you on Slack.

**Comment by ghost** [comment] 2018-09-18 17:29
@patbossman - you the man!

**Comment by patbossman** [comment] 2018-09-28 19:37
I do still reproduce this and killed nodeServer today - I will caution that I can also run for awhile without it.  I don't have a clean "if I do this, nodeServer goes crazy" trigger.

**Comment by ifakhrutdinov** [comment] 2018-10-01 06:17
@patbossman , to reproduce this issue a node instance has to create a message queue with a small ID value (e.g. 0x0000000A). Once it's done, it'll start looping when one of its file descriptors has the same ID value as the message queue.

One way to achieve that is:
* Start node, look at the "ipcs -q" output, if the lower two bytes of the node's message queue ID is relatively small, then stop node. If it's large, than one of the other message queues with lower ID values (only the lower 2 bytes matter in this step) will need to be removed so that node can use it when it's restarted. Let's say you pick the message queue with ID 0x0009000A.
* The higher two bytes of the message queue ID should be zeros. To do that write a simple C program that creates and deletes a message queue until its higher 2 bytes have value 0x7FFF.
* Start node, its message queue ID will be 0x0000000A because the 2 higher bytes of that 0x7FFF000A ID have overflowed.

**Comment by patbossman** [comment] 2018-10-01 12:08
@ifakhrutdinov ... how do I get the code?  It's been my experience once I hit it, even stop/start of the nodeServer, it is still looping.  So I would prefer to install the new node in a user directory, when I reproduce, I will kill the nodeServer and restart with the new node and validate it naturally.

**Comment by ifakhrutdinov** [comment] 2018-10-01 12:32
@patbossman, the new code can be found on the following branch https://github.com/ifakhrutdinov/node/tree/high-cpu-usage-fix (there is a PR https://github.com/ibmruntimes/node/pull/109), I can also provide the new binaries I built for z/OS.

**Comment by patbossman** [comment] 2018-10-01 12:57
@ifakhrutdinov I'm not sure how to build from source at the moment, it would certainly delay being able to check it out.  If I could get the new binaries, that would be great.

**Comment by philippe-richard** [comment] 2018-10-11 07:20
when i run npm install -g npm@5.4.2, then i get:
#npm install -dd -g npm@5.4.2
?øÁ>ËËÄ?>ÃÑÅÃ/ÑÁÀÁÊÊ?ÊËËÈÁ_%ÑÂÊ/ÊÃ?øÁ>áàäñ+?ËÍÄÇÃÑ%Á?ÊÀÑÊÁÄÈ?Ê`npm info it worked if it ends with ok
npm verb cli [ '/Z23R01/usr/lpp/IBM/node/node-v6.14.3-os390-s390x/bin/node',
npm verb cli '/var/zowe/0.9.0/EPHAN/tmp/bin/npm',
npm verb cli 'install',
npm verb cli '-dd',
npm verb cli '-g',
npm verb cli 'npm@5.4.2' ]
npm info using npm@5.4.2
npm info using node@v6.14.3
npm verb npm-session 6b1387b32cd0cc4a
npm http fetch GET 304 https://registry.npmjs.org/npm 763ms (from cache)
[..................] \ loadRequestedDeps: sill install loadAllDepsIntoIdealTree

and then it freezes, or loops. 
When i look at the process generated from our z/OS monitor (SDSF), then i see that the process is using up a full CPU (25%, and i have 4 CPs defined), and doing many I/Os
JOBNAME CPU% ASID ASIDX EXCP-Cnt CPU-Time
PRICHAR 24.45 107 006B 30710457 284.47

**Comment by philippe-richard** [comment] 2018-10-11 07:22
btw, as you can see from the above display,  i already have npm 5.4.2 (which i installed locally and manually), but i had the same behavior with npm 3.10.10 which comes imbedded in nodejs 6.14.3 for z/OS

**Comment by ifakhrutdinov** [comment] 2018-10-12 11:25
I can see the new version of Node.js (v6.14.4) available, does it include the fix merged in https://github.com/ibmruntimes/node/pull/109?

**Comment by joransiu** [comment] 2018-10-12 13:31
@ifakhrutdinov : Yes... the 6.14.4.0 driver on [DeveloperWorks](https://developer.ibm.com/node/sdk/ztp/) does contain the fix.    The corresponding SMP/E installable should be out shortly.

**Comment by philippe-richard** [comment] 2018-10-12 13:33
ok will try to install it later today, and will report back. Thanks


Cordialement, Philippe
  ====================

Philippe richard1/France/IBM@IBMFR (n'oubliez pas le 1...)
IBM Client Center, Montpellier

mailto:philippe_richard@fr.ibm.com   Mail: Cie IBM France Sce 146301
Phone: +33 4 6799580705 (38 0705)    Rue de la Vieille Poste -CS 81021
Fax:       +33 4 67346477                      34060 Montpellier Cedex  2

**Comment by joransiu** [comment] 2018-10-12 13:39
@philippe-richard : Yeah, please let me know if you still hit this hang issue with 6.14.4.  If so, ping me on Slack, and I can work with you to collect some diagnostics.

**Comment by philippe-richard** [comment] 2018-10-12 13:58
Hi Jioran, could not spot your ID on the slack channel for ZOWE. What's 
your id/name ?


Cordialement, Philippe
  ====================

Philippe richard1/France/IBM@IBMFR (n'oubliez pas le 1...)
IBM Client Center, Montpellier

mailto:philippe_richard@fr.ibm.com   Mail: Cie IBM France Sce 146301
Phone: +33 4 6799580705 (38 0705)    Rue de la Vieille Poste -CS 81021
Fax:       +33 4 67346477                      34060 Montpellier Cedex  2

**Comment by philippe-richard** [comment] 2018-10-12 14:43
Hey Joran
Good catch ! bingo ! it now works lile a charm. No longer any CPU burning 
problem, and when i run 'npm install -g npm@5.4.2', it went to completion, 
and i now have npm 5.4.2 installed and working
thanks for helping out on this issue


Cordialement, Philippe
  ====================

Philippe richard1/France/IBM@IBMFR (n'oubliez pas le 1...)
IBM Client Center, Montpellier

mailto:philippe_richard@fr.ibm.com   Mail: Cie IBM France Sce 146301
Phone: +33 4 6799580705 (38 0705)    Rue de la Vieille Poste -CS 81021
Fax:       +33 4 67346477                      34060 Montpellier Cedex  2

**Comment by philippe-richard** [comment] 2018-10-12 15:03
all npm problems and CPU looping are solved after installing nodejs 4.16.4. You may clode the issue

**Comment by joransiu** [comment] 2018-10-17 21:13
@eamondawes : Hopefully @ifakhrutdinov's fix from https://github.com/ibmruntimes/node/pull/109 resolves your high CPU usage too with the 6.14.4 driver.  Please re-open if that's not the case.  Thanks!

**Closed as completed by joransiu** 2018-10-17 21:13 UTC
Labels: zOS, fixed

**Comment by philippe-richard** [comment] 2018-10-18 06:16
yes my issue with high cpu usage has been solved with node 6.14.4


Cordialement, Philippe
  ====================

Philippe richard1/France/IBM@IBMFR (n'oubliez pas le 1...)
IBM Client Center, Montpellier

mailto:philippe_richard@fr.ibm.com   Mail: Cie IBM France Sce 146301
Phone: +33 4 6799580705 (38 0705)    Rue de la Vieille Poste -CS 81021
Fax:       +33 4 67346477                      34060 Montpellier Cedex  2
