### ISSUE TITLE
z/OS: node-gyp fails when node installed on filesystem with $VERSION in the path

### ISSUE THREAD

**Issue by matthewpwilson** [ibmruntimes/node#107] opened 2018-07-20 14:05 UTC
When running npm install for a native module with node installed in the default location under /usr/lpp,
on one particular system the resolved path includes the $VERSION symbol (I believe this relates to shared zFS).   It appears node-gyp mangles this somehow, see output below.
If I instead install the node SDK in my home directory and put that in my PATH, npm install works OK. 

> hello_world@0.0.0 install /u/wilson/abi-stable-node-addon-examples-master/1_hello_world/nan
> node-gyp rebuild

make: Entering directory '/u/wilson/abi-stable-node-addon-examples-master/1_hello_world/nan/build'
  CXX(target) Release/obj.target/hello/hello.o
  SOLINK_MODULE(target) Release/obj.target/hello.node
FSUM3228 njsc++: Input file /ERSION/usr/lpp/IBM/cnj/IBM/node-v6.14.2-os390-s390x/lib/libnode.x not found.
hello.target.mk:120: recipe for target 'Release/obj.target/hello.node' failed
make: *** [Release/obj.target/hello.node] Error 252
make: Leaving directory '/u/wilson/abi-stable-node-addon-examples-master/1_hello_world/nan/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/$VERSION/usr/lpp/IBM/cnj/IBM/node-v6.14.2-os390-s390x/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System OS/390 25.00
gyp ERR! command "/ZOS202/usr/lpp/IBM/cnj/IBM/node-v6.14.2-os390-s390x/bin/node" "/$VERSION/usr/lpp/IBM/cnj/IBM/node-v6.14.2-os390-s390x/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /u/wilson/abi-stable-node-addon-examples-master/1_hello_world/nan
gyp ERR! node -v v6.14.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! OS/390 25.00
npm ERR! argv "/ZOS202/usr/lpp/IBM/cnj/IBM/node-v6.14.2-os390-s390x/bin/node" "/usr/lpp/IBM/cnj/IBM/node-v6.14.2-os390-s390x/bin/npm" "install" "-V"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! hello_world@0.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hello_world@0.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hello_world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hello_world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hello_world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /u/wilson/abi-stable-node-addon-examples-master/1_hello_world/nan/npm-debug.log

**Comment by jBarz** [comment] 2018-07-24 15:28
A fix has been verified to work.
That fix has been commited here https://github.com/ibmruntimes/node/commit/bd5f46ae7d758c85d40984ba470424fd1174dd23
It should be available in the next release (after 6.14.3)

**Comment by joransiu** [comment] 2018-10-16 16:44
This issue should be resolved with 6.14.4 that is now available.  @matthewpwilson: Can you please confirm the problem is resolved?  Thanks.

**Comment by joransiu** [comment] 2018-10-17 17:29
@matthewpwilson : I'm going to close this issue as fixed.  Re-open if this persist in your environment or you have other concerns.

**Closed as completed by joransiu** 2018-10-17 17:29 UTC
Labels: zOS, fixed
