### ISSUE TITLE
npm install -g loopback-connector-dashdb2 fails on z/OS

### ISSUE THREAD

**Issue by smartmouse** [ibmruntimes/node#80] opened 2016-12-13 20:15 UTC
/u/slbld>npm install -g loopback-connector-dashdb
\
> ibm_db@1.0.1 install /u/slbld/node_global/lib/node_modules/loopback-connector-dashdb/node_modules/loopback-ibmdb/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//os390s390x_odbc_cli.tar.gz...
Unable to download IBM ODBC and CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//os390s390x_odbc_cli.tar.gz
npm ERR! Öâaóùð òôKðð
npm ERR! argv "/u/slbld/node/bin/node" "/u/slbld/node/bin/npm" "install" "-g" "loopback-connector-dashdb"
npm ERR! node v0.12.17
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@1.0.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@1.0.1 install script 'node installer/driverInstall.js'.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ibm_db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /u/slbld/npm-debug.log
:/u/slbld>

wonder of the db2 pacakges support z/OS?

**Comment by smartmouse** [comment] 2016-12-14 04:16
similar issues for loopback-connector-db2


/u/slbld>npm install -g loopback-connector-db2
\
> ibm_db@1.0.1 install /u/slbld/node_global/lib/node_modules/loopback-connector-db2/node_modules/loopback-ibmdb/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//os390s390x_odbc_cli.tar.gz...
Unable to download IBM ODBC and CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//os390s390x_odbc_cli.tar.gz
npm ERR! Öâaóùð òôKðð
npm ERR! argv "/u/slbld/node/bin/node" "/u/slbld/node/bin/npm" "install" "-g" "loopback-connector-db2"
npm ERR! node v0.12.17
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@1.0.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@1.0.1 install script 'node installer/driverInstall.js'.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ibm_db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /u/slbld/npm-debug.log
:/u/slbld>

**Comment by joransiu** [comment] 2016-12-14 04:28
Thanks @smartmouse.  All of these are related to ibm_db module, and the lack of z/OS cli drivers on DHE atm.  This issue is a duplicate of https://github.com/ibmruntimes/node/issues/74.  

I'll close this issue, and continue to update https://github.com/ibmruntimes/node/issues/74 as we make progress.  

/cc @bimalkjha

**Closed as completed by joransiu** 2016-12-14 04:28 UTC
